export default [
  //מסעדות
  {
    id: 4,
    name: "Reubens ",
    typeOfService: 2,
    phone: "0523311648",
    address: "79 Baker Street",
    city: "London",
    country: "United Kingdom",
    "area ID": "W1U 6RG",
    cosher: "KF",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 18,
    name: "Hummus Bar",
    typeOfService: 2,
    phone: "0589996632",
    address: "82 Golders Green Road",
    city: "London",
    country: "United Kingdom",
    "area ID": "NW11 8LN",
    cosher: "KF",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 19,
    name: "White Fish",
    typeOfService: 2,
    phone: "0514444795",
    address: "10-12 Bell Lane Hendon",
    city: "London",
    country: "United Kingdom",
    "area ID": "NW4 2AD",
    cosher: "KLBD",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 20,
    name: "  Pizaza",
    typeOfService: 2,
    phone: "0579996688",
    address: "100 Golders Green Road Golders Green",
    city: "London",
    country: "United Kingdom",
    "area ID": "NW11 8HB",
    cosher: "KF",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 21,
    name: "Sami's Kosher",
    typeOfService: 2,
    phone: "0596656658",
    address: "157 Brent Street",
    city: "London",
    country: "United Kingdom",
    "area ID": "NW4 4DJ",
    cosher: "KLBD",
    zipCode: "55",
    radius: 20,
  },
  //hotel
  {
    id: 1,
    name: "Ramada",
    typeOfService: 1,
    phone: "0523666874",
    address: "6 Ze'ev Vilnay St",
    city: "Jerusalem",
    country: "Israel",
    "area ID": "9611003",
    manager: "David",
    stars: "4",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 2,
    name: "Hilton",
    typeOfService: 1,
    phone: "0548963377",
    address: "205 HaYarkon St",
    city: "Tel Aviv",
    country: "Israel",
    "area ID": "6340534",
    manager: "Avi",
    stars: "5",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 5,
    name: "eeeee",
    typeOfService: 1,
    phone: "undefined",
    address: "undefined",
    city: "undefined",
    country: "Israel",
    "area ID": null,
    manager: "undefined",
    stars: "undefined",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 6,
    name: "Dan Accadia",
    typeOfService: 1,
    phone: "0526669988",
    address: "Ramat Yam 122 St",
    city: "Herzliya ",
    country: "Israel",
    "area ID": "4685623",
    manager: "Shalom",
    stars: "5",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 7,
    name: "Crowne Plaza",
    typeOfService: 1,
    phone: "0002222233",
    address: "136 Menahem Begin Rd",
    city: "Tel Aviv",
    country: "Israel",
    "area ID": "6701104",
    manager: "Yosi",
    stars: "4",
    zipCode: "55",
    radius: 20,
  },
  ///singugw
  {
    id: 22,
    name: "Netzach Yisrael",
    typeOfService: 5,
    phone: "0523333369",
    address: "Ibn Ezra St 22",
    city: "Jerusalem",
    country: "Israel",
    "area ID": "9242422",
    rabbi: "Michel Berniker",
    nusach: "Ashkenaz",
    community: "Orthodox",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 23,
    name: "Itzkovitch",
    typeOfService: 5,
    phone: "0598887789",
    address: "Rav Shach street",
    city: " Bnei Brak",
    country: "Israel",
    "area ID": "5136904",
    rabbi: "David",
    nusach: "Ashkenaz",
    community: "Orthodox",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 36,
    name: "Great Synagogue",
    typeOfService: 5,
    phone: "0556722288",
    address: "47 Hertzel",
    city: "Ramat Gan",
    country: "Israel",
    "area ID": "5245253",
    rabbi: "Asher",
    nusach: "Masorti",
    community: "Orthodox",
    zipCode: "55",
    radius: 20,
  },
  ///tours
  {
    id: 46,
    name: "City of David",
    typeOfService: 4,
    phone: "0554448899",
    address: "Ma’alot Ir David Street",
    city: "Jerusalem",
    country: "Israel",
    "area ID": "9710600",
    guide: "Nadav ",
    phoneGuide: "0586669393",
    placeOfDeparture: "Entrance to the reserve",
    duration: "2-2.5 hours",
    level: "family fun",
    age: "+5",
    description: null,
    zipCode: "55",
    radius: 20,
  },
  {
    id: 47,
    name: "Kol Shofar",
    typeOfService: 4,
    phone: "0737823272",
    address: "Givat Yoav",
    city: "Ramat HaGolan",
    country: "Israel",
    "area ID": "1294600",
    guide: "Shimon Keinan",
    phoneGuide: "0521114747",
    placeOfDeparture: "factory",
    duration: "1 hour",
    level: " easy",
    age: "No age limit",
    description:
      "מפעל משפחתי לייצור שופרות.המספק הצצה נדירה לעולם ייצור השופרות.",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 48,
    name: "Beit HaTfuztot",
    typeOfService: 4,
    phone: "073-7824030",
    address: "Tel Aviv University Campus-Klausner Street",
    city: "Tel Aviv ",
    country: "Israel",
    "area ID": "6901100",
    guide: "Israel",
    phoneGuide: "0536663636",
    placeOfDeparture: "museum lobby",
    duration: "4-5 hour",
    level: " profound",
    age: "No age limit",
    description:
      "מוזיאון העם היהודי, מספר על תרבות העם היהודי ומהווה מוסד עולמי ולו תפקיד חשוב בחיזוק הזהות היהודית ובהנצחת המורשת היהודית בעולם כולו.",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 49,
    name: "Kal Daat",
    typeOfService: 4,
    phone: "073-782-4149",
    address: "1 HaTayarut St.",
    city: " Moshav Aloni HaBashan",
    country: "Israel",
    "area ID": "1241200",
    guide: " Michael",
    phoneGuide: "0511112323",
    placeOfDeparture: "Entrance to the reserve",
    duration: "1-2 hours",
    level: " hard",
    age: "+16",
    description: "טיולי סגווי שטח בגולן",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 50,
    name: "De Karina",
    typeOfService: 4,
    phone: "073-782-3551",
    address: "",
    city: "Kibbutz Ein Zivan",
    country: "Israel",
    "area ID": "1242600",
    guide: "Yoav",
    phoneGuide: "0524447896",
    placeOfDeparture: "factory",
    duration: "1-2 hour",
    level: "easy & fun",
    age: "+3",
    description: "במפעל שוקולד דה-קרינה תוכלו לצאת לסיור בעולם השוקולד",
    zipCode: "55",
    radius: 20,
  },
  {
    id: 51,
    name: "Coca-Cola Sensory Center",
    typeOfService: 4,
    phone: "073-782-4597",
    address: "Rabbi Kahneman 129",
    city: "Bnei Brak",
    country: "Israel",
    "area ID": "5155366",
    guide: " Natan",
    phoneGuide: "0523332145",
    placeOfDeparture: "factory",
    duration: "1.5 hours",
    level: "easy & fun",
    age: "+7",
    description:
      'הסיפור של קוקה-קולה, מהיום שבו הומצא המשקה בבית המזיגה של ד"ר פמברטון, דרך הסיפור הגלובאלי, הזווית הישראלית, עולמות התוכן של המותג וסיור באחד מקווי הייצור החדשניים והמתקדמים ביותר בעולם.',
    zipCode: "55",
    radius: 20,
  },
];
